// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHr3nkwifL0Nae4Kic_3bhBZz1TbiK6Tk',
    appId: '1:210456685376:web:44a9782a735c7fda24a8a5',
    messagingSenderId: '210456685376',
    projectId: 'exskeleton-eg',
    authDomain: 'exskeleton-eg.firebaseapp.com',
    storageBucket: 'exskeleton-eg.firebasestorage.app',
    measurementId: 'G-YYVX2CZ3CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrUsB27hdRz9x8rZ-sdMnIh-XdpOI4Oug',
    appId: '1:210456685376:android:7f8db51ed10ed83324a8a5',
    messagingSenderId: '210456685376',
    projectId: 'exskeleton-eg',
    storageBucket: 'exskeleton-eg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRX4Gb31LLHwXcdpnrE5foGFsAGDc3pB0',
    appId: '1:210456685376:ios:55a729a130939fcf24a8a5',
    messagingSenderId: '210456685376',
    projectId: 'exskeleton-eg',
    storageBucket: 'exskeleton-eg.firebasestorage.app',
    iosBundleId: 'com.flutter.nextai.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRX4Gb31LLHwXcdpnrE5foGFsAGDc3pB0',
    appId: '1:210456685376:ios:59a3277ad7f3743624a8a5',
    messagingSenderId: '210456685376',
    projectId: 'exskeleton-eg',
    storageBucket: 'exskeleton-eg.firebasestorage.app',
    iosBundleId: 'hungps.com.flutterStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHr3nkwifL0Nae4Kic_3bhBZz1TbiK6Tk',
    appId: '1:210456685376:web:67c7a14432e7b98124a8a5',
    messagingSenderId: '210456685376',
    projectId: 'exskeleton-eg',
    authDomain: 'exskeleton-eg.firebaseapp.com',
    storageBucket: 'exskeleton-eg.firebasestorage.app',
    measurementId: 'G-TNLVYCWBD6',
  );
}
